### PR TITLE
Comment test 1

### PR DESCRIPTION
**Pull request by nwtgck**

### CODE REVIEW

**Comment by nwtgck** [comment]
@github-actions run

```js
console.log("hello, world");
```

**Comment by nwtgck** [comment]
@github-actions run

```js
(async () => {
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `Time from GitHub Actions: ${new Date()}`
  })
})();
```

**Comment by nwtgck** [comment]
@github-actions run

```js
(async () => {
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `Time from GitHub Actions: ${new Date()}`
  })
})();
```

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>Current time</summary>

```js
(async () => {
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `Time from GitHub Actions: ${new Date()}`
  })
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

```js
console.log("hello, world");
```

**Comment by pullreq-man** [comment]
@github-actions run

```js
console.log("hello, world");
```

**Comment by nwtgck** [comment]
@github-actions

```sh
#! /bin/sh
echo "hello"
```

**Comment by nwtgck** [comment]
@github-actions run

```js
const child_process = require('child_process');
const proc = child_process.spawn('ls -l');
console.log(proc);
```

**Comment by nwtgck** [comment]
```sh
#! /bin/sh
echo "hello, world"
```

```sh
#! /bin/sh
which python
which ruby
```

**Comment by nwtgck** [comment]
@github-actions run

```py
#! /usr/bin/python
import numpy as np

print(np.array([1, 2, 3]))
```

**Comment by nwtgck** [comment]
@github-actions run

```sh
#! /bin/sh
curl -L https://deno.land/x/install/install.py | python
which deno
```

(from: https://scrapbox.io/keroxp/deno%E5%85%A5%E9%96%802018)

**Comment by nwtgck** [comment]
@github-actions run

```sh
which runhaskell
```

**Comment by nwtgck** [comment]
@github-actions

```sh
#! /bin/sh

which go
```

**Comment by nwtgck** [comment]
@github-actions run

```sh
#! /bin/sh
sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/Ammonite/releases/download/2.0.4/2.13-2.0.4) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm' && amm
```

**Comment by nwtgck** [comment]
@github-actions run

```js

const body = `\
@github-actions run

\`\`\`sh
#! /bin/sh
echo hello
\`\`\`
`;

(async () => {
   await githubClient.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body,
        });
})();
```

**Comment by nwtgck** [comment]
```sh
#! /bin/sh
npm i -g ts-node
which ts-node
```

```ts
const str: string = "hello, world";
console.log(str);
```

**Comment by nwtgck** [comment]
@github-actions run


```js
(async () =>{
const res = await fetch("https://lgtm.in/g");
console.log(res);
})();

```

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `![LGTM](${picUrl.href})`,
  });
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `![LGTM](${picUrl.href})`,
  });
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `![LGTM](${picUrl.href})`,
  });
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `![LGTM](${picUrl.href})`,
  });
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `![LGTM](${picUrl.href})`,
  });
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `![LGTM](${picUrl.href})`,
  });
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `![LGTM](${picUrl.href})`,
  });
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `![LGTM](${picUrl.href})`,
  });
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `![LGTM](${picUrl.href})`,
  });
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `![LGTM](${picUrl.href})`,
  });
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `![LGTM](${picUrl.href})`,
  });
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `![LGTM](${picUrl.href})`,
  });
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `![LGTM](${picUrl.href})`,
  });
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `![LGTM](${picUrl.href})`,
  });
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await postComment(`![LGTM](${picUrl.href})`);
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await postComment(`![LGTM](${picUrl.href})`);
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  console.log(picUrl);
  await postComment(`![LGTM](${picUrl.href})`);
})();
```
</details>

**Comment by nwtgck** [comment]
@github-actions

```js
postComment("hello, world");
```

**Comment by nwtgck** [comment]
@github-actions run

```js
const lodash = require('lodash');
console.log(lodash);
```

**Comment by nwtgck** [comment]
@github-actions run

```js
console.log('hello, world');
```

**Comment by pullreq-man** [comment]
@github-actions run

```js
console.log('hello, world');
```

**Comment by pullreq-man** [comment]
@github-actions run

```js
postComment("hello, world");
```

**Comment by nwtgck** [comment]
@github-actions run

```js
(async () => {
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `hello, world`
  })
})();
```

**Comment by nwtgck** [comment]
@github-actions run

```js
(async () => {
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `hello, world`
  })
})();
```

**Comment by nwtgck** [comment]
@github-actions run

```sh
#! /bin/sh
pip install numpy
```

```py
#! /usr/bin/python
import numpy as np

print(np.array([1, 2, 3]))
```

**Comment by qbantek** [comment]
@github-actions run

```js
(async () => {
  await githubClient.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: `hello, world`
  })
})();
```

**Pull request closed without merging**
